### PR TITLE
fixing non reproducibility issue with cmaes inverse model

### PR DESCRIPTION
**Pull request by jgrizou**
Tricky one! For my work, I will run code on a real platform over multiple days. It requires to restart an experiment exaclty as I left it, hence to control the random seed. But the cmamodel and cma code did not handle seed yet. This pull request propose a solution for this. Tested on my system, the cma execution is now reproducible

- problem was call to np.random.seed() without seed due to none provided
- when this happen the seed is set according to some random value from the OS, which we can not control
- seed is now included in cmamodel.py (default to 0) and cma.py code is fixed to accept seed=0 as real seed
- seed is incremented every call so the initial population is not always the same

### CODE REVIEW

**Comment by sebastien-forestier** [comment]
Indeed we want to keep reproducibility.

However, I don't see why we would change the numpy.random seed on the fly, either in the previous cma version or in the patch you suggest.

I would rather remove the lines that change the seed in cma, and let the user decide to change the seed before running the algorithm.

For instance, when I want to run several trials of the same condition, I set a different seed in each trial. 

What do you think ?

**Comment by jgrizou** [comment]
Hmmm the thing is that seeding is all over the place in cma, so it might take quite some effort to remove it all and test. And it might be useful to run cma itself with seed functionality.

> For instance, when I want to run several trials of the same condition, I set a different seed before each trial

Well the seed is still accessible as a parameter for the model params:

```python
MODEL_PARAMS = {'fwd': 'LWLR', 'k': 10, 'inv': 'CMAES', 'cmaes_sigma': 0.05, 'maxfevals': 20, 'seed': 12}
```

Would that be enough for you? 

Otherwise the best option is probably to implement the np.random.set_state() in cma. And give np.random.get_state() as an option in cma bypassing the 'seed' arguments...

**Comment by jgrizou** [comment]
Just to clarify, the fact that the seed is re-set each time you call cmaes does not impact the validy of the seed you set at the beginning of each experiments.

**Comment by humm** [comment]
Hey,

Should you want to precisely control the random generator of a particular model, *independently* of the rest of the program, the best way is to create a `numpy.random.RandomState` instance and using this instance of all the random calls inside the model. Usually, calling `np.random.seed()` multiple times is a bad idea.

If you need to restart a paused experiment, the way to do it is with calls to `get_state()` and `set_state()`. In particular, `get_state()` may not necessarily equivalent to a given seed.

**Comment by humm** [comment]
`cma` does seem to intefer with the global `np.random.seed`:

https://github.com/jgrizou/explauto/blob/2c0526f461add2c63228f5778ca8aaaec71fa248/explauto/sensorimotor_model/inverse/cma.py#L2894

**Comment by jgrizou** [comment]
Hi @humm,

Yes, the thing is we (at least I) do not want to recode the cma code (8000 lines), and the all explauto, to handle random geenration from a ```numpy.random.RandomState```. And cma was reseting the seed arbitrarily, basically from the clock actually, so providing a seed is a good enough fix I think.

**Comment by humm** [comment]
Yeah, I understand.

**Comment by jgrizou** [comment]
Actually you are right @sebastien-forestier, I tried to remove all call to np.random.seed() without argument when seed is None. This way the seed is not set at all and the random generator remain in the same state. So now seed default to none in cmamodel.

Seems to work fine here. If you can check I did not forget some that would be nice.

**Comment by sebastien-forestier** [comment]
Thanks @jgrizou I think it is the best way.
I looked into the code and I found other calls to np.random.seed(self.seed) in classes ConstRandnShift and UnknownFF, which are part of the FFWrapper and if I understand well, is not used by our standard calls to fmin:

class FFWrapper
    """
    A collection of (yet experimental) classes to implement fitness
    transformations and wrappers. Aliased to `FF2` below.
    """

So to conclude I would accept your patch as it is!

**Comment by sebastien-forestier** [comment]
Anymore thoughts before merging ?

**Comment by jgrizou** [comment]
All fine for me

**Comment by humm** [comment]
Yep, sounds great.

**Pull request merged**
